### ISSUE TITLE
Error when command is sent

### ISSUE THREAD

**Issue by Sjokomelk** [Jarva-TD/GroupR#1]
[ERROR] addons/groupr/lua/autorun/server/groupr.lua:54: attempt to call global 'fancy_time_format' (a nil value)
1. fn - addons/groupr/lua/autorun/server/groupr.lua:54
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:183

name: !group

**Comment by Jarva** [comment]
https://github.com/Jarva-TD/GroupR/commit/de10764ac31d69021e48dbfcf5900f9551baab14
