### ISSUE TITLE
groupr.lua - attempt to index local 'data' (a nil value)

### ISSUE THREAD

**Issue by Zverina** [Jarva-TD/GroupR#5]
![error](https://cloud.githubusercontent.com/assets/9141783/5334781/0efc735a-7e4f-11e4-8388-e6b14d3b6972.png)

Appears when players join the group. They do not get their rewards (group change + pointshop points). It worked in the past, but it stopped working at some point. I do not know when this started, but it has been around for quite some time.

**Comment by Jarva** [comment]
https://github.com/Jarva-TD/GroupR/commit/66b2f1b44e633198fb9f874526b65ebf17c6010b
